all:
	@ruby no_me_quemes.rb 2026-05-01 2026-05-26 | grep -vi propietario | grep -vi profesor

beron:
	@ruby no_me_quemes.rb 2026-05-21 2026-05-31 | egrep -i '(beron|funes)'

obra:
	@ruby no_me_quemes.rb 2023-09-01 2025-07-31 | egrep -i '(obrero|material|volquet)'
